Repository beyond-sw-camp/beyond-sw-camp-be01_last-dance, pull requests merged in 2024-03, with the labels that each got.

#7 [T5] 팀역할분담 및 Organization 주소
  README.md
Labels: TEAM05, merge

#8 [T1] 집단 지성 활용을 위한 지식 관리 시스템 팀 역할 분담
  README.md
Labels: TEAM01, merge

#5 [T2] Team Repo 생성, 역할 분담 및 목표 수립
  README.md
Labels: TEAM02, merge

#6 [T3] 프로젝트 팀빌딩 역할 분담 - 11:10 PR 생성 ( v0.1.0 )
  README.md
Labels: TEAM03, merge

#4 [T4] 공급망 관리를 위한 주문관리시스템 역할분담
  README.md
Labels: TEAM04, merge

#20 통합 ground rule
  README.md
Labels: merge

#23 통합 ground rule 오류 수정
  README.md
Labels: merge

#33 [T5] personal-goals
  README.md
Labels: TEAM05, merge

#34 [T3] - personal-goals
  README.md
Labels: TEAM03, merge

#16 [9-13579] 프로젝트 팀 목표 수립
  README.md
Labels: TEAM03, merge, review

#35 [T5] tea-time
  README.md
Labels: TEAM05, merge

#24 [T2] Team Goal
  README.md
Labels: TEAM02, merge, review

#27 [T2] Team Personal Goals
  README.md
Labels: TEAM02, merge, review

#28 [T4]team goal 업로드
  README.md
Labels: TEAM04, review

#36 [T3] tea time
  README.md
Labels: TEAM03, merge

#39 [T4] personal-goals 업로드
  README.md
Labels: TEAM04, merge

#42 [T1] personal goals
  README.md
Labels: TEAM01, merge, conflict

#40 [T1] team goal
  README.md
Labels: TEAM01, merge, conflict

#29 [T2] Tea Time
  README.md
Labels: TEAM02, merge, review, conflict

#30 [T5] Team Goal & 역할 수정
  README.md
Labels: TEAM05, merge, review, conflict

#37 [3/04] Ground Rule 회의 - 변경사항
  README.md
Labels: merge, AC, conflict

#60 md -> html conversion using pandoc
  README.md
  github-pandoc.css
  index.html
Labels: 공유, 협업
